Sprint 11. Add database.
AndreyAFedotov/java-filmorate pull request #4
Opened 2023-07-02 22:22 UTC by AndreyAFedotov

2023-07-03 19:26 UTC, Frilock requested changes
Молодец Андрей, пара придирок ,а так все окей.

2023-07-03 19:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Не знаю, писал до этого или нет, но вообще предлагаю инициализировать коллекции сразу, дабы избегать лишних проверок на null в коде.

2023-07-03 19:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        } else {
Блок else не нужен, поскольку внутри if вы бросаете исключение, так что тут просто пишите return result

2023-07-03 19:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        Genre genre = genreStorage.getGenre(id);
Вообще можете попробовать возвращать Optional, тогда данный метод будет куда компактнее

2023-07-03 19:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/DBFilmStorage.java
> +    public static final String FILM_ID = "FILM_ID";
А они еще где то используются вне класса? Почему публичные?

2023-07-03 19:26 UTC, Frilock commented on src/main/resources/data.sql
> +
Много лишних пустых строк в конце файла

2023-07-03 19:26 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS MPAS
Между creataми 1 строчку пустую пропустите, чтобы читалось проще

2023-07-03 19:45 UTC, AndreyAFedotov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Исправил.

2023-07-03 19:47 UTC, AndreyAFedotov commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        } else {
Исправил. В MpaService тоже.

2023-07-03 19:48 UTC, AndreyAFedotov commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        Genre genre = genreStorage.getGenre(id);
Я бы пока оставил так, если можно... как-то привычнее )

2023-07-03 19:49 UTC, AndreyAFedotov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/DBFilmStorage.java
> +    public static final String FILM_ID = "FILM_ID";
Исправил. В DBUserStorage тоже.

2023-07-03 19:50 UTC, AndreyAFedotov commented on src/main/resources/data.sql
> +
Удалил

2023-07-03 19:55 UTC, AndreyAFedotov commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS MPAS
Готово

2023-07-04 04:54 UTC, Frilock approved these changes
Принято

2023-07-04 06:30 UTC, merged